# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
        ('itineraries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='trip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='trips.Trip'),
            preserve_default=False,
        ),
    ]
