# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itineraries', '0002_itinerary_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='date',
            field=models.DateField(),
        ),
    ]
