# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon_name',
            new_name='icon',
        ),
    ]
