# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='activity',
            name='currency',
            field=models.CharField(blank=True, choices=[('CAD', 'CAD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('KRW', 'KRW'), ('USD', 'USD')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='activity',
            name='directions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
