# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20170317_0201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='activity',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='itineraries.Itinerary'),
        ),
    ]
